export { default as HomePage } from "./HomePage"
export { default as LoginPage } from "./LoginPage"
export { default as SignUpPage } from "./SignUpPage"
export { default as ProfilePage } from "./ProfilePage"
export { default as SingleGamePage } from "./SingleGamePage"
export { default as UsersDashboardPage } from "./UsersDashboardPage"
export { default as GamesDashboardPage } from "./GamesDashboardPage"
export { default as OrdersDashboardPage } from "./OrdersDashboardPage"
